export const styles = {
  page: {
    minHeight: "100dvh",
    display: "flex",
    justifyContent: "center",
    padding: "16px 12px 32px",
    boxSizing: "border-box",
  },
  mobileShell: {
    width: "100%",
    maxWidth: "420px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  heroCard: {
    background: "linear-gradient(180deg, #1d4ed8 0%, #2563eb 100%)",
    color: "white",
    padding: "18px",
    borderRadius: "20px",
    boxShadow: "0 10px 24px rgba(37,99,235,0.22)",
  },
  heroTitle: {
    margin: 0,
    fontSize: "28px",
    lineHeight: 1.1,
  },
  heroText: {
    marginTop: "6px",
    marginBottom: "18px",
    opacity: 0.9,
  },
  sectionCard: {
    background: "white",
    padding: "16px",
    borderRadius: "18px",
    boxShadow: "0 8px 20px rgba(0,0,0,0.06)",
  },
  chartCard: {
    background: "white",
    padding: "16px",
    borderRadius: "18px",
    boxShadow: "0 8px 20px rgba(0,0,0,0.06)",
  },
  chartTitle: {
    fontSize: "20px",
    fontWeight: 800,
    marginBottom: "12px",
  },
  chartWrap: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    alignItems: "center",
  },
  pie: {
    width: "180px",
    height: "180px",
    borderRadius: "50%",
    border: "12px solid white",
    boxShadow: "inset 0 0 0 1px #e5e7eb",
  },
  legend: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  legendRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  legendSwatch: {
    width: "12px",
    height: "12px",
    borderRadius: "999px",
  },
  legendText: {
    fontSize: "14px",
  },
  noData: {
    color: "#5e6167",
    padding: "12px 0",
  },
  sectionTitle: {
    margin: 0,
    fontSize: "20px",
    fontWeight: 800,
  },
  mutedText: {
    color: "#6b7280",
    marginTop: "8px",
    marginBottom: 0,
  },
  label: {
    display: "block",
    marginTop: "12px",
    marginBottom: "6px",
    fontWeight: 700,
    fontSize: "14px",
  },
  input: {
    width: "100%",
    minHeight: "50px",
    padding: "12px 14px",
    fontSize: "16px",
    borderRadius: "14px",
    border: "1px solid #d1d5db",
    boxSizing: "border-box",
    background: "white",
  },
  primaryButton: {
    marginTop: "16px",
    width: "100%",
    minHeight: "50px",
    border: "none",
    borderRadius: "16px",
    fontSize: "16px",
    fontWeight: 700,
    background: "#2563eb",
    color: "white",
    cursor: "pointer",
  },
  deleteRoundButtonLarge: {
    width: "100%",
    minHeight: "50px",
    border: "none",
    borderRadius: "16px",
    fontSize: "16px",
    fontWeight: 700,
    background: "#d45555",
    color: "white",
    cursor: "pointer",
  },
  buttonRow: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "10px",
    marginTop: "10px",
  },
  roundList: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    marginTop: "8px",
  },
  roundListItem: {
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: "16px",
    padding: "10px",
  },
  roundMainButton: {
    width: "100%",
    background: "transparent",
    border: "none",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    textAlign: "left",
    padding: "4px 0",
    cursor: "pointer",
  },
  roundCourse: {
    fontWeight: 700,
    fontSize: "16px",
  },
  roundDate: {
    color: "#6b7280",
    fontSize: "14px",
    marginTop: "3px",
  },
  roundChevron: {
    fontSize: "28px",
    color: "#9ca3af",
    lineHeight: 1,
  },
  deleteRoundButton: {
    marginTop: "10px",
    width: "100%",
    minHeight: "42px",
    borderRadius: "12px",
    border: "1px solid #fecaca",
    background: "#fff1f2",
    color: "#b91c1c",
    fontWeight: 700,
    cursor: "pointer",
  },
  playHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "12px",
  },
  playCourse: {
    fontSize: "20px",
    fontWeight: 800,
  },
  playDate: {
    color: "#6b7280",
    marginTop: "4px",
    fontSize: "14px",
  },
  holeCounter: {
    background: "#dbeafe",
    color: "#1d4ed8",
    borderRadius: "999px",
    padding: "8px 12px",
    fontWeight: 700,
    fontSize: "14px",
    whiteSpace: "nowrap",
  },
  parRow: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "8px",
    marginTop: "8px",
  },
  parButton: {
    minHeight: "52px",
    borderRadius: "14px",
    border: "1px solid #d1d5db",
    background: "white",
    fontSize: "18px",
    fontWeight: 800,
    cursor: "pointer",
  },
  parButtonActive: {
    background: "#2563eb",
    color: "white",
    border: "1px solid #2563eb",
  },
  segmentedWrap: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
    marginTop: "8px",
  },
  segmentedButton: {
    minHeight: "50px",
    borderRadius: "14px",
    border: "1px solid #d1d5db",
    background: "white",
    fontSize: "15px",
    fontWeight: 700,
    cursor: "pointer",
  },
  segmentedActive: {
    background: "#2563eb",
    color: "white",
    border: "1px solid #2563eb",
  },
  twoColGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
  },
  toggleCard: {
    width: "100%",
    marginTop: "12px",
    minHeight: "84px",
    borderRadius: "16px",
    border: "1px solid #d1d5db",
    background: "white",
    padding: "14px",
    cursor: "pointer",
    textAlign: "left",
  },
  toggleCardActive: {
    background: "#eff6ff",
    border: "1px solid #60a5fa",
  },
  toggleCardLabel: {
    fontSize: "14px",
    color: "#6b7280",
  },
  toggleCardValue: {
    marginTop: "10px",
    fontSize: "22px",
    fontWeight: 800,
  },
  shotCardList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginTop: "8px",
  },
  shotCard: {
    border: "1px solid #e5e7eb",
    borderRadius: "18px",
    padding: "14px",
    background: "#fafafa",
  },
  shotCardActive: {
    background: "#eff6ff",
    border: "2px solid #93c5fd",
  },
  shotCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "10px",
  },
  shotNumber: {
    fontWeight: 800,
    fontSize: "17px",
  },
  puttToggleRow: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    alignItems: "flex-end",
  },
  puttToggle: {
    border: "1px solid #d1d5db",
    background: "white",
    color: "#111827",
    borderRadius: "999px",
    padding: "8px 12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  puttToggleActive: {
    background: "#16a34a",
    color: "white",
    border: "1px solid #16a34a",
  },
  removeGhostButton: {
    border: "none",
    background: "transparent",
    color: "#dc2626",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "14px",
  },
  puttInfoBox: {
    marginTop: "12px",
    fontSize: "14px",
    color: "#166534",
    background: "#f0fdf4",
    padding: "10px 12px",
    borderRadius: "12px",
    border: "1px solid #bbf7d0",
  },
  shotPenaltyInfo: {
    marginTop: "12px",
    fontSize: "14px",
    color: "#374151",
    background: "#f3f4f6",
    padding: "10px 12px",
    borderRadius: "12px",
  },
  summaryBox: {
    marginTop: "14px",
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    borderRadius: "16px",
    padding: "14px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  summaryInline: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    fontSize: "15px",
  },
  bottomActionBar: {
    marginTop: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    paddingBottom: "16px",
  },
  primaryAction: {
    width: "100%",
    minHeight: "52px",
    border: "none",
    borderRadius: "16px",
    fontSize: "17px",
    fontWeight: 800,
    background: "#2563eb",
    color: "white",
    cursor: "pointer",
  },
  secondaryActionsRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    marginTop: "10px",
  },
  secondaryAction: {
    minHeight: "48px",
    borderRadius: "14px",
    border: "1px solid #d1d5db",
    background: "white",
    fontWeight: 700,
    cursor: "pointer",
  },
  dangerAction: {
    minHeight: "48px",
    borderRadius: "14px",
    border: "none",
    background: "#dc2626",
    color: "white",
    fontWeight: 700,
    cursor: "pointer",
  },
  ghostAction: {
    marginTop: "10px",
    width: "100%",
    minHeight: "44px",
    borderRadius: "14px",
    border: "1px solid #e5e7eb",
    background: "#f9fafb",
    color: "#374151",
    fontWeight: 700,
    cursor: "pointer",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "10px",
    marginTop: "14px",
  },
  statCard: {
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: "16px",
    padding: "14px",
  },
  statValue: {
    fontSize: "22px",
    fontWeight: 800,
  },
  statLabel: {
    marginTop: "6px",
    fontSize: "13px",
    color: "#6b7280",
  },
  scorecardSection: {
    marginTop: "12px",
  },
  scorecardHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  scorecardTitle: {
    fontWeight: 800,
    fontSize: "16px",
  },
  scorecardSubtotal: {
    fontWeight: 700,
    color: "#374151",
  },
  scorecardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "8px",
  },
  scoreCell: {
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: "14px",
    padding: "10px",
    textAlign: "center",
  },
  scoreHoleNo: {
    fontSize: "12px",
    color: "#6b7280",
    marginBottom: "6px",
  },
  scoreBadge: {
    width: "44px",
    height: "44px",
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: "18px",
  },
  scoreBadgeSmall: {
    width: "26px",
    height: "26px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "4px",
    marginLeft: "10px",
    fontSize: "11px",
    fontWeight: 800,
  },
  scoreSymbol: {
    marginTop: "6px",
    fontSize: "11px",
    color: "#4b5563",
  },
  scoreEagle: {
    borderRadius: "50%",
    border: "3px double #16a34a",
    background: "#f0fdf4",
    color: "#166534",
  },
  scoreBirdie: {
    borderRadius: "50%",
    border: "2px solid #2563eb",
    background: "#eff6ff",
    color: "#1d4ed8",
  },
  scorePar: {
    borderRadius: "12px",
    border: "1px solid #d1d5db",
    background: "white",
    color: "#111827",
  },
  scoreBogey: {
    borderRadius: "4px",
    border: "2px solid #f59e0b",
    background: "#fffbeb",
    color: "#92400e",
  },
  scoreDouble: {
    borderRadius: "4px",
    border: "3px double #dc2626",
    background: "#fef2f2",
    color: "#991b1b",
  },
  scoreLegend: {
    marginTop: "14px",
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    alignItems: "center",
    fontSize: "12px",
    color: "#4b5563",
  },
  headerSparklineCard: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "18px",
    padding: "14px",
    marginBottom: "20px",
  },
  headerSparklineLabel: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: "10px",
  },
  headerSparklinePlaceholder: {
    height: "72px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "12px",
    background: "#f9fafb",
    color: "#111827",
    fontSize: "13px",
  },
  homeButtonStack: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  selectInput: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: "12px",
    border: "1px solid #d1d5db",
    fontSize: "15px",
    background: "#fff",
  },
  textInput: {
    flex: 1,
    padding: "12px 14px",
    borderRadius: "12px",
    border: "1px solid #d1d5db",
    fontSize: "15px",
    background: "#fff",
  },
  inlineRow: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
  },
  tagRow: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginTop: "10px",
  },
  tagChip: {
    border: "1px solid #d1d5db",
    background: "#f9fafb",
    borderRadius: "999px",
    padding: "8px 12px",
    fontSize: "13px",
    cursor: "pointer",
  },

  inRoundHeader: {
    background: "#eef6ee",
    border: "1px solid #d7e7d7",
    borderRadius: "16px",
    padding: "14px 16px",
    marginBottom: "16px",
  },

  inRoundHeaderTop: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#1f2937",
    marginBottom: "6px",
  },

  inRoundHeaderBottom: {
    fontSize: "13px",
    color: "#4b5563",
    fontWeight: 600,
  },

  inRoundCenterWrap: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "24px",
  },

  inRoundSideLeft: {
    position: "fixed",
    left: "20px",
    top: "50%",
    transform: "translateY(-50%)",
  },

  inRoundSideRight: {
    position: "fixed",
    right: "20px",
    top: "50%",
    transform: "translateY(-50%)",
  },

  sideNavButton: {
    minHeight: "120px",
    minWidth: "56px",
    borderRadius: "18px",
    border: "1px solid #cbd5e1",
    background: "#111827",
    color: "#ffffff",
    fontWeight: 700,
    padding: "12px",
    cursor: "pointer",
  },

  inRoundBottomLeft: {
    position: "fixed",
    left: "20px",
    bottom: "20px",
  },

  inRoundBottomRight: {
    position: "fixed",
    right: "20px",
    bottom: "20px",
  },

  cornerNavButton: {
    minWidth: "110px",
    minHeight: "48px",
    borderRadius: "14px",
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#111827",
    fontWeight: 700,
    cursor: "pointer",
  },

  inRoundFooterInfo: {
    marginTop: "10px",
    fontSize: "14px",
    color: "#4b5563",
    fontWeight: 600,
  },
  parSelectorWrap: {
  marginBottom: "16px",
  },

  parButtonRow: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "8px",
  },
  distanceWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "10px",
  },

  distanceDisplay: {
    fontSize: "22px",
    fontWeight: 800,
    background: "#eef2ff",
    padding: "10px 18px",
    borderRadius: "12px",
    border: "1px solid #c7d2fe",
  },

  keypad: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 60px)",
    gap: "8px",
  },

  keypadButton: {
    height: "44px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#fff",
    fontWeight: 700,
    cursor: "pointer",
  },
}